-- LedgerFlowPro — multi-user upgrade.
-- Run this once in Supabase: SQL Editor > New query > Run.
-- Safe to run even if you already ran the old (single-password) version of
-- this file before — it only adds what's missing.

create sequence if not exists public.bill_no_seq start with 1;

create table if not exists public.parties (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.bills (
    id bigint generated by default as identity primary key,
    bill_no text not null unique default ('BILL-' || lpad(nextval('public.bill_no_seq')::text, 4, '0')),
    date date not null,
    party text not null,
    launch text not null check (length(trim(launch)) > 0),
    bill_amt numeric(14,2) not null check (bill_amt > 0),
    remarks text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    bill_id bigint not null references public.bills(id) on delete cascade,
    date date not null,
    amount numeric(14,2) not null check (amount > 0),
    note text not null default '',
    created_at timestamptz not null default now()
);

-- 1) Give every table an "owner" column. New rows fill this in automatically
--    with whoever is logged in (auth.uid()). Existing rows (if any) will be
--    NULL for now, which simply means nobody can see them anymore until you
--    claim them — see the note at the bottom of this file.
alter table public.parties  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.bills    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.payments add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.parties  alter column user_id set default auth.uid();
alter table public.bills    alter column user_id set default auth.uid();
alter table public.payments alter column user_id set default auth.uid();

-- 2) A party name should only be unique per user, not across everyone.
alter table public.parties drop constraint if exists parties_name_key;
drop index if exists parties_user_name_key;
create unique index parties_user_name_key on public.parties (user_id, name);

-- 3) Remove the old "anyone with the password can see everything" policies.
drop policy if exists "test app parties" on public.parties;
drop policy if exists "test app bills" on public.bills;
drop policy if exists "test app payments" on public.payments;

-- 4) Turn on Row Level Security and only allow logged-in users to see /
--    change rows that belong to them.
alter table public.parties  enable row level security;
alter table public.bills    enable row level security;
alter table public.payments enable row level security;

create policy "own parties" on public.parties
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "own bills" on public.bills
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "own payments" on public.payments
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- OPTIONAL — only if you already had test bills/parties from before and
-- want to keep them under your own new account:
--   1. Sign up in the app once so your account exists.
--   2. In Supabase: Authentication > Users, copy your new user's UUID.
--   3. Run (replace the UUID):
--        update public.parties  set user_id = 'PASTE-YOUR-UUID-HERE' where user_id is null;
--        update public.bills    set user_id = 'PASTE-YOUR-UUID-HERE' where user_id is null;
--        update public.payments set user_id = 'PASTE-YOUR-UUID-HERE' where user_id is null;
-- ---------------------------------------------------------------------

-- ---------------------------------------------------------------------
-- 5) Per-user bill numbering. Every account now gets its own counter
--    starting at BILL-0001, instead of everyone sharing one global
--    counter (which used to make bill numbers jump around between
--    different users' accounts).
-- ---------------------------------------------------------------------

alter table public.bills alter column bill_no drop default;
alter table public.bills drop constraint if exists bills_bill_no_key;
drop index if exists bills_bill_no_key;
create unique index if not exists bills_user_bill_no_key on public.bills (user_id, bill_no);

create table if not exists public.user_bill_counters (
    user_id uuid primary key references auth.users(id) on delete cascade,
    next_no integer not null default 1
);
alter table public.user_bill_counters enable row level security;
drop policy if exists "own counter" on public.user_bill_counters;
create policy "own counter" on public.user_bill_counters
    for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- If any existing account already has bills, carry their counter forward
-- instead of resetting them back to 0001 (only matters for accounts that
-- already had bills before this change).
insert into public.user_bill_counters (user_id, next_no)
select user_id, coalesce(max(nullif(regexp_replace(bill_no, '\D', '', 'g'), '')::int), 0) + 1
from public.bills
where user_id is not null
group by user_id
on conflict (user_id) do update set next_no = greatest(public.user_bill_counters.next_no, excluded.next_no);

create or replace function public.assign_bill_no()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    n integer;
begin
    insert into public.user_bill_counters (user_id, next_no)
    values (new.user_id, 2)
    on conflict (user_id) do update set next_no = public.user_bill_counters.next_no + 1
    returning next_no - 1 into n;

    new.bill_no := 'BILL-' || lpad(n::text, 4, '0');
    return new;
end;
$$;

drop trigger if exists trg_assign_bill_no on public.bills;
create trigger trg_assign_bill_no
    before insert on public.bills
    for each row execute function public.assign_bill_no();

