-- Run this once in Supabase: SQL Editor > New query > Run.
create sequence if not exists public.bill_no_seq start with 1;

create table if not exists public.parties (
    id bigint generated by default as identity primary key,
    name text not null unique check (length(trim(name)) > 0),
    created_at timestamptz not null default now()
);

create table if not exists public.bills (
    id bigint generated by default as identity primary key,
    bill_no text not null unique default ('BILL-' || lpad(nextval('public.bill_no_seq')::text, 4, '0')),
    date date not null,
    party text not null,
    launch text not null check (length(trim(launch)) > 0),
    bill_amt numeric(14,2) not null check (bill_amt > 0),
    remarks text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    bill_id bigint not null references public.bills(id) on delete cascade,
    date date not null,
    amount numeric(14,2) not null check (amount > 0),
    note text not null default '',
    created_at timestamptz not null default now()
);

-- Required for a simple customer-test app using the anonymous key.
alter table public.parties enable row level security;
alter table public.bills enable row level security;
alter table public.payments enable row level security;

create policy "test app parties" on public.parties for all to anon using (true) with check (true);
create policy "test app bills" on public.bills for all to anon using (true) with check (true);
create policy "test app payments" on public.payments for all to anon using (true) with check (true);

insert into public.parties (name) values ('Nasir'), ('Mehmood'), ('Muzaffar')
on conflict (name) do nothing;
